import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LogoutButton } from "./components/LogoutButton";
import { getUser } from "./lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex p-5 gap-6 border-b">
          {!user && <div className="flex gap-6 items-center">
            <Link href={'/login'}>Login</Link>
            <Link href={'/signup'}>Sign Up</Link>
          </div>}
          {user &&
            <div className="flex gap-6 items-center">
              <Link href={'/dashboard'}>Dashboard</Link>
              <LogoutButton />
            </div>}
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
